import { storage } from './storage';

const INITIAL_CATEGORIES = [
  { name: 'LLM Platforms', collapsed: false, toolIds: [], sortOrder: 0 },
  { name: 'Image Generation', collapsed: false, toolIds: [], sortOrder: 1 },
  { name: 'Code & Dev', collapsed: false, toolIds: [], sortOrder: 2 },
  { name: 'Creative & Writing', collapsed: false, toolIds: [], sortOrder: 3 },
  { name: 'Audio & Video', collapsed: false, toolIds: [], sortOrder: 4 },
  { name: 'Agents & Automation', collapsed: false, toolIds: [], sortOrder: 5 },
];

// Helper function to generate random trend data
const generateTrend = (): number[] => {
  const base = Math.floor(Math.random() * 50) + 30;
  return Array(7).fill(0).map(() => base + Math.floor(Math.random() * 30) - 15);
};

const INITIAL_TOOLS = [
  // ==================== CHATBOT (8) ====================
  {
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    type: 'CHATBOT',
    summary: 'Conversational AI model developed by OpenAI. Used for various tasks including Q&A, content generation, and more.',
    tags: ['LLM', 'Prod'],
    categoryId: '',
    isPinned: true,
    icon: '💬',
    whatItIs: 'A conversational AI model developed by OpenAI that uses deep learning.',
    capabilities: ['Text generation', 'Code writing', 'Q&A', 'Summarization'],
    bestFor: ['General queries', 'Writing', 'Coding'],
    status: 'active',
    contentType: 'tool',
    trend: [45, 52, 58, 62, 65, 70, 75],
    usage: 95,
  },
  {
    name: 'Claude',
    url: 'https://claude.ai',
    type: 'CHATBOT',
    summary: 'Anthropic AI assistant focused on safety and helpfulness.',
    tags: ['LLM', 'Safe'],
    categoryId: '',
    isPinned: true,
    icon: '🤖',
    whatItIs: 'AI assistant built by Anthropic with constitutional AI principles.',
    capabilities: ['Long context', 'Analysis', 'Coding', 'Writing'],
    bestFor: ['Research', 'Coding', 'Document analysis'],
    status: 'active',
    contentType: 'tool',
    trend: [40, 48, 55, 58, 62, 68, 72],
    usage: 88,
  },
  {
    name: 'Gemini',
    url: 'https://gemini.google.com',
    type: 'CHATBOT',
    summary: 'Google Multimodal AI model with advanced reasoning.',
    tags: ['LLM', 'Multi'],
    categoryId: '',
    isPinned: false,
    icon: '✨',
    whatItIs: 'Google flagship multimodal AI model.',
    capabilities: ['Multimodal', 'Code', 'Reasoning', 'Search integration'],
    bestFor: ['Research', 'Code', 'Analysis'],
    status: 'active',
    contentType: 'tool',
    trend: [35, 42, 50, 55, 60, 65, 70],
    usage: 82,
  },
  {
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    type: 'CHATBOT',
    summary: 'AI search engine combining LLM with real-time web search.',
    tags: ['Search', 'LLM'],
    categoryId: '',
    isPinned: true,
    icon: '🔍',
    whatItIs: 'AI-powered search engine with citations.',
    capabilities: ['Real-time search', 'Citations', 'Follow-up'],
    bestFor: ['Research', 'Fact-checking', 'Current events'],
    status: 'active',
    contentType: 'tool',
    trend: [30, 38, 45, 55, 60, 68, 75],
    usage: 78,
  },
  {
    name: 'GPT-4 Turbo',
    url: 'https://platform.openai.com',
    type: 'CHATBOT',
    summary: 'OpenAI most capable model with 128K context window.',
    tags: ['LLM', 'API'],
    categoryId: '',
    isPinned: false,
    icon: '⚡',
    whatItIs: 'Enhanced GPT-4 model with longer context.',
    capabilities: ['128K context', 'Vision', 'JSON mode'],
    bestFor: ['Long docs', 'Development', 'Enterprise'],
    status: 'active',
    contentType: 'tool',
    trend: [50, 55, 60, 62, 65, 68, 72],
    usage: 85,
  },
  {
    name: 'GPT-4o',
    url: 'https://openai.com/gpt-4o',
    type: 'CHATBOT',
    summary: 'OpenAI multimodal model with native audio capabilities.',
    tags: ['LLM', 'Multi', 'Voice'],
    categoryId: '',
    isPinned: false,
    icon: '🎯',
    whatItIs: 'Multimodal GPT-4 with voice and vision.',
    capabilities: ['Voice input', 'Vision', 'Real-time'],
    bestFor: ['Voice apps', 'Multimodal', 'Consumer'],
    status: 'active',
    contentType: 'tool',
    trend: [25, 35, 45, 55, 62, 70, 78],
    usage: 75,
  },
  {
    name: 'Claude 3 Opus',
    url: 'https://anthropic.com/claude',
    type: 'CHATBOT',
    summary: 'Anthropic most powerful model for complex tasks.',
    tags: ['LLM', 'Ent'],
    categoryId: '',
    isPinned: false,
    icon: '🏛️',
    whatItIs: 'Top-tier Claude model for demanding tasks.',
    capabilities: ['Complex analysis', 'Long context', 'Nuanced writing'],
    bestFor: ['Enterprise', 'Research', 'Complex tasks'],
    status: 'active',
    contentType: 'tool',
    trend: [40, 45, 50, 52, 55, 58, 62],
    usage: 70,
  },
  {
    name: 'Claude 3.5 Sonnet',
    url: 'https://claude.ai',
    type: 'CHATBOT',
    summary: 'Best balance of speed and intelligence for coding.',
    tags: ['LLM', 'Code', 'Fast'],
    categoryId: '',
    isPinned: true,
    icon: '🎵',
    whatItIs: 'Optimal Claude model for development.',
    capabilities: ['Code gen', 'Analysis', 'Fast'],
    bestFor: ['Coding', 'Productivity', 'Chat'],
    status: 'active',
    contentType: 'tool',
    trend: [55, 60, 65, 70, 75, 80, 85],
    usage: 92,
  },

  // ==================== IMAGE (6) ====================
  {
    name: 'Midjourney',
    url: 'https://midjourney.com',
    type: 'IMAGE',
    summary: 'AI image generation via Discord with exceptional artistic styles.',
    tags: ['Creative', 'Art'],
    categoryId: '',
    isPinned: true,
    icon: '🎨',
    whatItIs: 'AI art generator accessible through Discord.',
    capabilities: ['Artistic styles', 'High quality', 'Variations'],
    bestFor: ['Art', 'Design', 'Concepts'],
    status: 'active',
    contentType: 'tool',
    trend: [60, 65, 68, 70, 72, 75, 78],
    usage: 90,
  },
  {
    name: 'DALL-E 3',
    url: 'https://openai.com/dall-e-3',
    type: 'IMAGE',
    summary: 'OpenAI latest image generation with excellent text rendering.',
    tags: ['Creative', 'Text'],
    categoryId: '',
    isPinned: false,
    icon: '🖼️',
    whatItIs: 'OpenAI state-of-the-art image generator.',
    capabilities: ['Text in images', 'Prompt understanding', 'Styles'],
    bestFor: ['Marketing', 'Content', 'Graphics'],
    status: 'active',
    contentType: 'tool',
    trend: [50, 55, 60, 65, 68, 72, 75],
    usage: 85,
  },
  {
    name: 'Stable Diffusion',
    url: 'https://stability.ai',
    type: 'IMAGE',
    summary: 'Open source image generation model with local deployment.',
    tags: ['Open', 'Local'],
    categoryId: '',
    isPinned: false,
    icon: '🌀',
    whatItIs: 'Open source image generation model.',
    capabilities: ['Open source', 'Local run', 'Customizable'],
    bestFor: ['Development', 'Custom models', 'Privacy'],
    status: 'active',
    contentType: 'tool',
    trend: [45, 48, 52, 55, 58, 60, 62],
    usage: 75,
  },
  {
    name: 'Flux Pro',
    url: 'https://blackforestlabs.ai',
    type: 'IMAGE',
    summary: 'Fast high-quality image generation with excellent prompt adherence.',
    tags: ['Creative', 'Fast'],
    categoryId: '',
    isPinned: false,
    icon: '⚡',
    whatItIs: 'High-quality image generation model.',
    capabilities: ['Speed', 'Quality', 'Consistency'],
    bestFor: ['Rapid iteration', 'Production', 'Quality'],
    status: 'active',
    contentType: 'tool',
    trend: [30, 40, 50, 58, 65, 72, 80],
    usage: 72,
  },
  {
    name: 'Leonardo',
    url: 'https://leonardo.ai',
    type: 'IMAGE',
    summary: 'AI art platform with custom training capabilities.',
    tags: ['Creative', 'Train'],
    categoryId: '',
    isPinned: false,
    icon: '🎭',
    whatItIs: 'Creative AI platform with fine-tuning.',
    capabilities: ['Custom models', 'Multiple styles', 'Training'],
    bestFor: ['Game dev', 'Consistent styles', 'Assets'],
    status: 'beta',
    contentType: 'tool',
    trend: [35, 42, 48, 52, 55, 58, 62],
    usage: 68,
  },
  {
    name: 'Ideogram',
    url: 'https://ideogram.ai',
    type: 'IMAGE',
    summary: 'AI image generation specialized in text rendering.',
    tags: ['Creative', 'Text'],
    categoryId: '',
    isPinned: false,
    icon: '📝',
    whatItIs: 'Image generator excelling at text in images.',
    capabilities: ['Text rendering', 'Logos', 'Typography'],
    bestFor: ['Logos', 'Marketing', 'Text-heavy'],
    status: 'active',
    contentType: 'tool',
    trend: [28, 35, 45, 52, 60, 68, 75],
    usage: 65,
  },

  // ==================== CODE (5) ====================
  {
    name: 'GitHub Copilot',
    url: 'https://github.com/features/copilot',
    type: 'CODE',
    summary: 'AI pair programmer that helps write code faster.',
    tags: ['Dev', 'IDE'],
    categoryId: '',
    isPinned: true,
    icon: '🐙',
    whatItIs: 'AI coding assistant integrated into IDE.',
    capabilities: ['Code completion', 'Suggestions', 'Docs'],
    bestFor: ['Daily coding', 'Boilerplate', 'Learning'],
    status: 'active',
    contentType: 'tool',
    trend: [55, 58, 62, 65, 68, 72, 75],
    usage: 88,
  },
  {
    name: 'Cursor',
    url: 'https://cursor.sh',
    type: 'CODE',
    summary: 'AI-first code editor built for pair programming with AI.',
    tags: ['Dev', 'Editor'],
    categoryId: '',
    isPinned: true,
    icon: '➤',
    whatItIs: 'VS Code fork with native AI integration.',
    capabilities: ['Chat', 'Edit', 'Codebase aware'],
    bestFor: ['Full projects', 'Refactoring', 'Learning'],
    status: 'active',
    contentType: 'tool',
    trend: [40, 50, 60, 70, 78, 85, 90],
    usage: 85,
  },
  {
    name: 'Replit AI',
    url: 'https://replit.com',
    type: 'CODE',
    summary: 'Browser-based IDE with AI code assistance.',
    tags: ['Dev', 'Cloud'],
    categoryId: '',
    isPinned: false,
    icon: '🌐',
    whatItIs: 'Cloud IDE with AI features.',
    capabilities: ['Browser-based', 'Multiplayer', 'Deploy'],
    bestFor: ['Quick projects', 'Learning', 'Collaboration'],
    status: 'active',
    contentType: 'tool',
    trend: [42, 45, 48, 52, 55, 58, 62],
    usage: 70,
  },
  {
    name: 'Codeium',
    url: 'https://codeium.com',
    type: 'CODE',
    summary: 'Free AI code completion for individual developers.',
    tags: ['Dev', 'Free'],
    categoryId: '',
    isPinned: false,
    icon: '🆓',
    whatItIs: 'Free AI coding assistant.',
    capabilities: ['Autocomplete', 'Chat', 'Multi-language'],
    bestFor: ['Individual devs', 'Cost savings', 'Multiple languages'],
    status: 'active',
    contentType: 'tool',
    trend: [35, 40, 45, 50, 55, 60, 65],
    usage: 65,
  },
  {
    name: 'Tabnine',
    url: 'https://tabnine.com',
    type: 'CODE',
    summary: 'AI code completion with privacy-focused options.',
    tags: ['Dev', 'Privacy'],
    categoryId: '',
    isPinned: false,
    icon: '🔒',
    whatItIs: 'Privacy-first AI coding assistant.',
    capabilities: ['Local models', 'Enterprise', 'Secure'],
    bestFor: ['Enterprise', 'Privacy', 'Compliance'],
    status: 'active',
    contentType: 'tool',
    trend: [38, 40, 42, 45, 48, 52, 55],
    usage: 58,
  },

  // ==================== WRITING (4) ====================
  {
    name: 'Notion AI',
    url: 'https://notion.so',
    type: 'WRITING',
    summary: 'AI writing features built into Notion workspace.',
    tags: ['Docs', 'Team'],
    categoryId: '',
    isPinned: false,
    icon: '📓',
    whatItIs: 'AI embedded in Notion.',
    capabilities: ['Summarize', 'Draft', 'Edit', 'Translate'],
    bestFor: ['Note-taking', 'Team docs', 'Productivity'],
    status: 'active',
    contentType: 'tool',
    trend: [48, 52, 55, 58, 62, 65, 68],
    usage: 75,
  },
  {
    name: 'Jasper',
    url: 'https://jasper.ai',
    type: 'WRITING',
    summary: 'AI writing assistant for marketing copy and content.',
    tags: ['Marketing', 'Content'],
    categoryId: '',
    isPinned: false,
    icon: '📢',
    whatItIs: 'Marketing-focused AI writer.',
    capabilities: ['Ad copy', 'Blog posts', 'Templates'],
    bestFor: ['Marketing', 'SEO', 'Scale content'],
    status: 'deprecated',
    contentType: 'tool',
    trend: [50, 48, 45, 42, 40, 38, 35],
    usage: 55,
  },
  {
    name: 'Copy.ai',
    url: 'https://copy.ai',
    type: 'WRITING',
    summary: 'AI copywriting tool for sales and marketing.',
    tags: ['Marketing', 'Sales'],
    categoryId: '',
    isPinned: false,
    icon: '✏️',
    whatItIs: 'AI copywriting assistant.',
    capabilities: ['Sales copy', 'Emails', 'Social'],
    bestFor: ['Sales teams', 'Marketers', 'Small biz'],
    status: 'active',
    contentType: 'tool',
    trend: [40, 42, 45, 48, 52, 55, 58],
    usage: 62,
  },
  {
    name: 'Grammarly',
    url: 'https://grammarly.com',
    type: 'WRITING',
    summary: 'AI writing assistant for grammar and style improvements.',
    tags: ['Writing', 'Grammar'],
    categoryId: '',
    isPinned: true,
    icon: '✅',
    whatItIs: 'Writing assistant with AI.',
    capabilities: ['Grammar', 'Tone', 'Clarity', 'Plagiarism'],
    bestFor: ['All writing', 'Professionals', 'Students'],
    status: 'active',
    contentType: 'tool',
    trend: [55, 58, 60, 62, 65, 68, 70],
    usage: 80,
  },

  // ==================== AGENT (4) ====================
  {
    name: 'AutoGPT',
    url: 'https://github.com/Significant-Gravitas/Auto-GPT',
    type: 'AGENT',
    summary: 'Autonomous AI agent that chains together tasks.',
    tags: ['Agent', 'Open'],
    categoryId: '',
    isPinned: false,
    icon: '🤖',
    whatItIs: 'Open source autonomous agent.',
    capabilities: ['Task chains', 'Web browse', 'Memory'],
    bestFor: ['Research', 'Automation', 'Experiments'],
    status: 'beta',
    contentType: 'tool',
    trend: [60, 55, 50, 48, 45, 42, 40],
    usage: 45,
  },
  {
    name: 'AgentGPT',
    url: 'https://agentgpt.reworkd.ai',
    type: 'AGENT',
    summary: 'Browser-based autonomous AI agent platform.',
    tags: ['Agent', 'Web'],
    categoryId: '',
    isPinned: false,
    icon: '🌐',
    whatItIs: 'Web-based autonomous agent.',
    capabilities: ['Browser-based', 'Task chains', 'Deploy'],
    bestFor: ['Quick tests', 'Non-technical', 'Demos'],
    status: 'active',
    contentType: 'tool',
    trend: [35, 40, 42, 45, 48, 50, 52],
    usage: 50,
  },
  {
    name: 'CrewAI',
    url: 'https://crewai.io',
    type: 'AGENT',
    summary: 'Framework for orchestrating AI agents working together.',
    tags: ['Agent', 'Framework'],
    categoryId: '',
    isPinned: false,
    icon: '👥',
    whatItIs: 'Multi-agent orchestration framework.',
    capabilities: ['Multi-agent', 'Role-based', 'Python'],
    bestFor: ['Complex tasks', 'Teams', 'Enterprise'],
    status: 'active',
    contentType: 'tool',
    trend: [25, 35, 45, 55, 65, 75, 82],
    usage: 60,
  },
  {
    name: 'LangChain',
    url: 'https://langchain.com',
    type: 'AGENT',
    summary: 'Framework for building LLM-powered applications.',
    tags: ['Framework', 'Dev'],
    categoryId: '',
    isPinned: false,
    icon: '🔗',
    whatItIs: 'LLM application framework.',
    capabilities: ['Chains', 'Agents', 'Memory', 'Tools'],
    bestFor: ['LLM apps', 'Developers', 'Prototyping'],
    status: 'active',
    contentType: 'tool',
    trend: [45, 50, 55, 60, 65, 70, 75],
    usage: 78,
  },

  // ==================== AUDIO (3) ====================
  {
    name: 'ElevenLabs',
    url: 'https://elevenlabs.io',
    type: 'AUDIO',
    summary: 'AI voice synthesis with realistic natural-sounding voices.',
    tags: ['Voice', 'TTS'],
    categoryId: '',
    isPinned: true,
    icon: '🔊',
    whatItIs: 'AI voice generation platform.',
    capabilities: ['Voice clone', 'TTS', 'Multiple languages'],
    bestFor: ['Content creators', 'Audiobooks', 'Games'],
    status: 'active',
    contentType: 'tool',
    trend: [50, 55, 60, 65, 70, 75, 80],
    usage: 85,
  },
  {
    name: 'Suno',
    url: 'https://suno.ai',
    type: 'AUDIO',
    summary: 'AI music generation from text prompts with vocals.',
    tags: ['Music', 'Creative'],
    categoryId: '',
    isPinned: false,
    icon: '🎵',
    whatItIs: 'AI music generator.',
    capabilities: ['Full songs', 'Vocals', 'Genres'],
    bestFor: ['Musicians', 'Content', 'Fun'],
    status: 'active',
    contentType: 'tool',
    trend: [35, 45, 55, 65, 72, 78, 85],
    usage: 75,
  },
  {
    name: 'Whisper',
    url: 'https://github.com/openai/whisper',
    type: 'AUDIO',
    summary: 'OpenAI speech recognition model for accurate transcription.',
    tags: ['STT', 'Open'],
    categoryId: '',
    isPinned: false,
    icon: '👂',
    whatItIs: 'Open source speech-to-text.',
    capabilities: ['Transcription', 'Multi-language', 'Local'],
    bestFor: ['Transcription', 'Subtitles', 'Accessibility'],
    status: 'active',
    contentType: 'tool',
    trend: [52, 55, 58, 60, 62, 65, 68],
    usage: 72,
  },

  // ==================== VIDEO (3) ====================
  {
    name: 'Runway',
    url: 'https://runwayml.com',
    type: 'VIDEO',
    summary: 'AI video generation and editing platform.',
    tags: ['Video', 'Creative'],
    categoryId: '',
    isPinned: true,
    icon: '🎬',
    whatItIs: 'AI video generation platform.',
    capabilities: ['Gen-2', 'Video edit', 'Motion'],
    bestFor: ['Filmmakers', 'Content', 'Ads'],
    status: 'active',
    contentType: 'tool',
    trend: [45, 52, 58, 65, 70, 75, 80],
    usage: 82,
  },
  {
    name: 'Pika',
    url: 'https://pika.art',
    type: 'VIDEO',
    summary: 'AI video generation with creative motion effects.',
    tags: ['Video', 'Art'],
    categoryId: '',
    isPinned: false,
    icon: '⚡',
    whatItIs: 'AI video generator.',
    capabilities: ['Text-to-video', 'Image-to-video', 'Effects'],
    bestFor: ['Social content', 'Quick videos', 'Creative'],
    status: 'active',
    contentType: 'tool',
    trend: [30, 40, 50, 60, 68, 75, 82],
    usage: 70,
  },
  {
    name: 'HeyGen',
    url: 'https://heygen.com',
    type: 'VIDEO',
    summary: 'AI avatar video creation for business and marketing.',
    tags: ['Video', 'Avatar'],
    categoryId: '',
    isPinned: false,
    icon: '👤',
    whatItIs: 'AI avatar video platform.',
    capabilities: ['Avatars', 'Multi-language', 'Templates'],
    bestFor: ['Training', 'Marketing', 'Scale video'],
    status: 'active',
    contentType: 'tool',
    trend: [42, 48, 55, 60, 65, 70, 75],
    usage: 68,
  },
];

async function seed() {
  try {
    console.log('Starting seed...');

    const existingCategories = await storage.getAllCategories();
    const existingTools = await storage.getAllTools();

    if (existingCategories.length > 0 || existingTools.length > 0) {
      console.log('Database already seeded. Skipping...');
      return;
    }

    const createdCategories = [];
    for (const cat of INITIAL_CATEGORIES) {
      const created = await storage.createCategory(cat);
      createdCategories.push(created);
      console.log(`Created category: ${created.name}`);
    }

    const categoryMap: Record<string, string> = {
      'LLM Platforms': createdCategories[0].id,
      'Image Generation': createdCategories[1].id,
      'Code & Dev': createdCategories[2].id,
      'Creative & Writing': createdCategories[3].id,
      'Audio & Video': createdCategories[4].id,
      'Agents & Automation': createdCategories[5].id,
    };

    // Map tool types to categories
    const typeToCategory: Record<string, string> = {
      'CHATBOT': 'LLM Platforms',
      'IMAGE': 'Image Generation',
      'CODE': 'Code & Dev',
      'WRITING': 'Creative & Writing',
      'AUDIO': 'Audio & Video',
      'VIDEO': 'Audio & Video',
      'AGENT': 'Agents & Automation',
    };

    for (const tool of INITIAL_TOOLS) {
      const categoryName = typeToCategory[tool.type] || 'LLM Platforms';
      const categoryId = categoryMap[categoryName];

      const created = await storage.createTool({ ...tool, categoryId });
      console.log(`Created tool: ${created.name} (${tool.type})`);

      const category = await storage.getCategory(categoryId);
      if (category) {
        await storage.updateCategory(categoryId, {
          toolIds: [...category.toolIds, created.id]
        });
      }
    }

    console.log('Seed completed successfully!');
    console.log(`Created ${INITIAL_CATEGORIES.length} categories and ${INITIAL_TOOLS.length} tools.`);
  } catch (error) {
    console.error('Seed failed:', error);
    throw error;
  }
}

seed();
